"""Initial migration with unified models

Revision ID: d10d7775e73d
Revises: 
Create Date: 2025-08-24 19:11:27.546367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd10d7775e73d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thermal_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tower_id', sa.Integer(), nullable=True),
    sa.Column('tower_name', sa.String(), nullable=True),
    sa.Column('camp_name', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('image_temp', sa.Float(), nullable=True),
    sa.Column('ambient_temp', sa.Float(), nullable=True),
    sa.Column('delta_t', sa.Float(), nullable=True),
    sa.Column('threshold_used', sa.Float(), nullable=True),
    sa.Column('fault_level', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('voltage_kv', sa.Integer(), nullable=True),
    sa.Column('capacity_amps', sa.Integer(), nullable=True),
    sa.Column('commissioning_year', sa.Integer(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.Column('analysis_status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thermal_reports_id'), 'thermal_reports', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_thermal_reports_id'), table_name='thermal_reports')
    op.drop_table('thermal_reports')
    # ### end Alembic commands ###
