name: Dependency Updates

on:
  schedule:
    # Run every Monday at 9:00 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch: # Allow manual triggering

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Check for Python dependency updates
      working-directory: ./backend
      run: |
        pip install pip-tools
        pip-compile --upgrade requirements.in || echo "No requirements.in file found"
    
    - name: Check for Node.js dependency updates
      working-directory: ./frontend
      run: |
        npm outdated || true
        npm audit --audit-level=moderate
    
    - name: Create issue for dependency updates
      if: failure()
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: 'Dependency Updates Available',
            body: 'Automated dependency check found updates or security issues. Please review and update dependencies.',
            labels: ['dependencies', 'security']
          });
